<?php
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
* Implements hook_entity_update().
*/

function dta_website_slack_integration_entity_update(Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node') {
      return;
    }

    if(isset($_ENV['ENVIRONMENT'])) {
       switch ($_ENV['ENVIRONMENT']) {
         case 'production':
         $nid = $entity->id();
         $node = Node::load($nid);
         $default_version_moderation = $node->moderation_state->value;
         $page_title = $entity->title->value;
         $full_url = Url::fromRoute('entity.node.canonical', ['node' => $nid], ['absolute' => TRUE])->toString();
         $lastest_version_url = "$base_url/node/$nid/latest";

         // Check if content moderation state is equal to 'technical_review'
         $current_entity_lang=$entity->get('langcode')->value;
         $translated_entity = $entity->getTranslation($current_entity_lang);
         $mod_state =$translated_entity->get('moderation_state')->getString();


      // Check if node has a default revision that is published
      // this will set the page url
       if ($default_version_moderation === 'published' ) {
         $page_url = $lastest_version_url;
       }
       else{
         $page_url = $full_url;
       }

       if ($mod_state === 'technical_review'){
           // Get Slack config
           $config = \Drupal::config('slack.settings');
           $channel = $config->get('slack_channel');
           $username = $config->get('slack_username');
           $webhook = $config->get('slack_webhook_url');
           // Set Slack message text
           $output = [];
           $output[] = "Hi! $page_title is ready for review";
           $output[] = "at $page_url";
           $output[] = "Jump in there now!";
           // Show message on site
           drupal_set_message(t('The moderation state is now `Technical review`. A slack message has been sent to the #dtagovau_authors slack channel.'));
           // Send message to Slack
          Drupal::service('slack.slack_service')
          ->sendMessage(implode("\n", $output),$webhook , $channel, $username);
    }

           break;
         case 'staging':
         // Getting latest moderation state of node
         $current_entity_lang=$entity->get('langcode')->value;
         $translated_entity = $entity->getTranslation($current_entity_lang);
         $mod_state =$translated_entity->get('moderation_state')->getString();

         if ($mod_state === 'technical_review'){
            // Show message on site
             drupal_set_message(t('The moderation state is now `Technical review`. This is a staging environment. A slack message has not been sent to the #dtagovau_authors slack channel.'));
           }

           break;
         case 'test':
         // Getting latest moderation state of node
         $current_entity_lang=$entity->get('langcode')->value;
         $translated_entity = $entity->getTranslation($current_entity_lang);
         $mod_state =$translated_entity->get('moderation_state')->getString();
         // Check if content moderation state is equal to 'technical_review'
         if ($mod_state === 'technical_review'){
           // Show message on site
             drupal_set_message(t('The moderation state is now `Technical review`. This is a test environment. A slack message has not been sent to the #dtagovau_authors slack channel.'));
           }
           break;
         }
        }
        else {
           // Getting latest moderation state of node
          $current_entity_lang=$entity->get('langcode')->value;
          $translated_entity = $entity->getTranslation($current_entity_lang);
          $mod_state =$translated_entity->get('moderation_state')->getString();

          // Check if content moderation state is equal to 'technical_review'
          if ($mod_state === 'technical_review'){
           // Show message on site
           drupal_set_message(t("The moderation state is now `Technical review`. This is a local environment. A slack message has not been sent to the #dtagovau_authors slack channel."));
         }
        ;}
      }

/**
* Implements hook_entity_insert().
*/

function dta_website_slack_integration_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

        if ($entity->getEntityTypeId() !== 'node') {
            return;
          }

          if(isset($_ENV['ENVIRONMENT'])) {
             switch ($_ENV['ENVIRONMENT']) {
               case 'production':
                 $nid = $entity->id();
                 $node = Node::load($nid);
                 $default_version_moderation = $node->moderation_state->value;
                 $page_title = $entity->title->value;
                 $full_url = Url::fromRoute('entity.node.canonical', ['node' => $nid], ['absolute' => TRUE])->toString();
                 $lastest_version_url = "$base_url/node/$nid/latest";
                 // Getting latest moderation state of node
                 $current_entity_lang=$entity->get('langcode')->value;
                 $translated_entity = $entity->getTranslation($current_entity_lang);
                 $mod_state =$translated_entity->get('moderation_state')->getString();

                 // Check if node has a default revision that is published
                 // this will set the page url to either
                  if ($default_version_moderation === 'published' ) {
                    $page_url = $lastest_version_url;
                  }
                  else{
                    $page_url = $full_url;
                  }

            // Check if content moderation state is equal to 'technical_review'
             if ($mod_state === 'technical_review'){
                 // Get Slack config
                 $config = \Drupal::config('slack.settings');
                 $channel = $config->get('slack_channel');
                 $username = $config->get('slack_username');
                 $webhook = $config->get('slack_webhook_url');
                 // Set Slack message text
                 $output = [];
                 $output[] = "Hi! $page_title is ready for review";
                 $output[] = "at $page_url";
                 $output[] = "Jump in there now!";
                 // Show message on site
                 drupal_set_message(t('The moderation state is now `Technical review`. A slack message has been sent to the #dtagovau_authors slack channel.'));
                 // Send message to Slack
                Drupal::service('slack.slack_service')
                ->sendMessage(implode("\n", $output),$webhook , $channel, $username);
          }

                 break;
               case 'staging':
               // Getting latest moderation state of node
               $current_entity_lang=$entity->get('langcode')->value;
               $translated_entity = $entity->getTranslation($current_entity_lang);
               $mod_state =$translated_entity->get('moderation_state')->getString();

               if ($mod_state === 'technical_review'){
                  // Show message on site
                   drupal_set_message(t('The moderation state is now `Technical review`. This is a staging environment. A slack message has not been sent to the #dtagovau_authors slack channel.'));
                 }

                 break;
               case 'test':
               // Getting latest moderation state of node
               $current_entity_lang=$entity->get('langcode')->value;
               $translated_entity = $entity->getTranslation($current_entity_lang);
               $mod_state =$translated_entity->get('moderation_state')->getString();
               // Check if content moderation state is equal to 'technical_review'
               if ($mod_state === 'technical_review'){
                 // Show message on site
                   drupal_set_message(t('The moderation state is now `Technical review`. This is a test environment. A slack message has not been sent to the #dtagovau_authors slack channel.'));
                 }
                 break;
               }
              }
              else {
                 // Getting latest moderation state of node
                $current_entity_lang=$entity->get('langcode')->value;
                $translated_entity = $entity->getTranslation($current_entity_lang);
                $mod_state =$translated_entity->get('moderation_state')->getString();

                // Check if content moderation state is equal to 'technical_review'
                if ($mod_state === 'technical_review'){
                 // Show message on site
                 drupal_set_message(t("The moderation state is now `Technical review`. This is a local environment. A slack message has not been sent to the #dtagovau_authors slack channel."));
               }
              ;}
            }
